---

- name: Load variables based on OS type
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "family-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "family-{{ ansible_os_family }}.yml"
        - default.yml
      paths:
        - 'vars'

- name: Install python3
  include_role:
    name: python
  vars:
    python2: false
    python3: true

- name: Uninstall python3 packages
  package:
    name: "{{ item }}"
    state: absent
  loop:
    - python3-pyyaml

- name: Install OS packages globally
  package:
    name: "{{ molecule_os_packages }}"
    state: present
  become: yes

- name: Install pip packages globally
  pip:
    name: "{{ molecule_pip_packages }}"
    state: present
  become: yes
  tags: molecule-idempotence-notest

- name: Install ansible/molecule into virtual environments
  include_role:
    name: python
  vars:
    python_virtualenv_root: "{{ molecule_venv_root }}"
    python_virtualenvs: "{{ molecule_venvs }}"
  tags: molecule-idempotence-notest

- name: Distribute all support scripts & files
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin/{{ item }}
    mode: "0755"
  loop:
    - molecule-test.sh
    - ansible-galaxy.sh
    - ansible-requirements-clean.sh
