---

- name: Load variables based on OS type
  ansible.builtin.include_tasks: vars.yml

- name: Install python3
  ansible.builtin.include_role:
    name: python
  vars:
    python2: false
    python3: true
    python38: "{{ molecule_python38 }}"
    python39: "{{ molecule_python39 }}"

- name: Uninstall python3 packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  loop:
    - python3-pyyaml

- name: Install OS packages globally
  ansible.builtin.package:
    name: "{{ molecule_os_packages }}"
    state: present
  become: yes

- name: Install pip packages globally
  ansible.builtin.pip:
    name: "{{ molecule_pip_packages }}"
    state: present
  become: yes
  tags: molecule-idempotence-notest

- name: Install ansible/molecule into virtual environments
  ansible.builtin.include_role:
    name: python
  vars:
    python_virtualenv_root: "{{ molecule_venv_root }}"
    python_virtualenvs: "{{ molecule_venvs }}"
  tags: molecule-idempotence-notest

- name: Distribute all support scripts & files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /usr/local/bin/{{ item }}
    mode: "0755"
  loop:
    - ansible-collections.sh
    - ansible-fix.sh
    - ansible-galaxy.sh
    - ansible-lint.sh
    - ansible-requirements-clean.sh
    - functions_ansible.sh
    - functions.sh
    - molecule-test.sh
