---

- name: Load variables based on OS type
  ansible.builtin.include_tasks: vars.yml

- name: Uninstall python3 packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  loop:
    - python3-pyyaml

- name: Install OS packages globally
  ansible.builtin.package:
    name: "{{ molecule_os_packages }}"
    state: present
  become: yes

- name: Include venv.yml
  ansible.builtin.include_tasks: venv.yml

- name: Include scripts.yml
  ansible.builtin.include_tasks: scripts.yml

- name: Include links.yml
  ansible.builtin.include_tasks: links.yml
