---

- name: Setup virtual enviromments
  ansible.builtin.include_role:
    name: deitkrachten.python
  vars:
    python_virtualenv_only: true
    python_virtualenv_root: "{{ molecule_venv_root }}"
    python_virtualenvs: "{{ molecule_venvs_empty }}"
  when: molecule_python_venv | bool
  tags: molecule-idempotence-notest

- name: Work-around for pyyaml
  ansible.builtin.pip:
    name:
      - "cython<3.0.0"
      - "pyyaml<6"
    executable: "{{ molecule_venv_root }}/{{ item.name }}/bin/pip3"
    extra_args: "--no-build-isolation"
  become: yes
  become_user: "{{ molecule_virtualenv_user | default('root') }}"
  loop: "{{ molecule_venvs_empty }}"

- name: Install ansible/molecule into virtual environments
  ansible.builtin.include_role:
    name: deitkrachten.python
  vars:
    python_virtualenv_only: true
    python_virtualenv_root: "{{ molecule_venv_root }}"
    python_virtualenvs: "{{ molecule_venvs }}"
  when: molecule_python_venv | bool
  tags: molecule-idempotence-notest
