---

- name: Converge
  hosts: all
  become: "yes"
  vars:
    molecule_python_install: True
  roles:
    - deitkrachten.python
    - deitkrachten.docker
  tasks:
    - name: Include role 'ansible-role-molecule'
      ansible.builtin.include_role:
        name: ansible-role-molecule
