---

name: CI

on:
  pull_request:
  push:
    branches-ignore:
      - master
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * 1"

defaults:
  run:
    working-directory: "de-it-krachten/ansible-role-molecule"


jobs:

  molecule:
    name: "${{ matrix.name }}"
    runs-on: "${{ matrix.runs_on }}"
    # continue-on-error: ${{ matrix.continue_on_error }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ubuntu2204
            runs_on: ubuntu-latest
            distro: ubuntu2204
            playbook: converge.yml
            ansible: "ansible-core>2.14,<2.15"
            ansible_lint: "ansible-lint>6,<7"
            hetznercloud: True

    steps:

      - name: Check out the codebase.
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"


      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'


      - name: Show runner info
        run: |
          hostname -f

      - name: Disable specific apparmor profiles
        run: |
          sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
          sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld

      - name: Install test dependencies.
        run: |
          sudo rm -f /usr/bin/yq
          pip3 install ansible-core
          git clone -b dev https://github.com/de-it-krachten/ansible-playbooks-runner /tmp/ansible-playbooks-runner
          cd /tmp/ansible-playbooks-runner
          export ANSIBLE_FORCE_COLOR=true
          ansible-galaxy install -r roles/requirements.yml -p roles/
          ansible-playbook runner.yml

      - name: Set-up github runner
        run: |
          sudo modprobe ip6table_filter

      - name: Show component versions
        run: |
          ansible --version
          ansible-lint --version
          yamllint --version
          molecule --version
